name: Imaginarium
favicon: null
layout_spectrum: 0.49666
typography_spectrum: 0.11519166990183294
title: Imaginarium
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#47413c'
    - '#4a687c'
    - '#9c904f'
    - '#bcbcc1'
  brandStrength: 0.5
  lightness: 0.9366537658497691
  saturation: 0.268762941705063
  rhythmicContrast: 0.3083353319671005
purpose: []
